# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
highlighter: true
markdown: kramdown
url: "http://www.tquizzle.com"
permalink: /archive/:title/
exclude: [LICENSE, CNAME, README.md, .gitignore]
title: TQuizzle.com
google_analytics_key: UA-253329-3
description: "ramblings, utterances, nonsense."


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: TQuizzle.com

author:
  name: TQuizzle
  #email: dbyll@ismaildemirbilek.com
  github: TQuizzle
  twitter: TQuizzle
  #pinterest: asd123
  #linkedin: asd123
  bio: "TQuizzle.com is my place to talk about whatever. I really don't post here much anymore what with all the other domains I own, but I'm putting it up on GitHub so that it can be seen for archive puposes."
  email_md5: 9ff9176cb3c383c60d7d91bf0dce141e

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
